### ISSUE TITLE
Add social sharing button for blog posts.

### ISSUE THREAD

**Issue by dxphilo** [Vuejs-Kenya/community-website#101]
The idea here is to make a feature that a user /reader can easily share the article to other social media platforms preferably (twitter,linkedin, reddit,facebook, e.t.c)

**Comment by dxphilo** [comment]
@james-muriithi you can work on this.

**Comment by james-muriithi** [comment]
okay

**Comment by dxphilo** [comment]
Closing this. PR #152  for reference
