### ISSUE TITLE
Upgrade `nuxt-content` from 1.15.1 --->> 2.0

### ISSUE THREAD

**Issue by dxphilo** [Vuejs-Kenya/community-website#108]

**Comment by dxphilo** [comment]
> can i work on this open issue

Yes sure assigning you the issue. Expecting you PR soon

**Comment by jacksonohallo** [comment]
`$content is not a function
An error occurred while rendering the page. Check developer tools console for details.`

Updating nuxt-content to v.2.0 will also require upgrade to nuxt 2

**Comment by dxphilo** [comment]
This issues should be closed by this PR #135
