### ISSUE TITLE
Add "Previous speakers" section to the landing page

### ISSUE THREAD

**Issue by grafitto** [Vuejs-Kenya/community-website#186]
Design
![image](https://user-images.githubusercontent.com/8601175/226913269-948fa38f-62e4-4faa-8b18-f7030cd8aa95.png)

[Figma designs](https://www.figma.com/file/Ot1DHtKMym97KvmSsx24Tk/VueKenya-Home-Page?node-id=0-1&t=VRYhj5Ka8N3HpZkZ-0)

Please use Homepage 3

I think past speakers should just be displayed, replacing the picture, become a speaker can open email app ready to send an email

**Comment by dxphilo** [comment]
Apart from the speaker image, I also added some extra info (name, socials, talk title). Thoughts ?
